version: 2.1
jobs:
  build:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout
      - run:
          name: Build project ne
          command: |
            xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"
      - store_artifacts:
          path: build/reports
      - store_artifacts:
          path: build/coverage

  unit-test:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout
      - run:
          name: Run unit tests ne
          command: |
            xcodebuild test -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13" -enableCodeCoverage YES



# version: 2.1

# jobs:
#   build:
#     macos:
#       xcode: "14.0.1"
#     steps:
#       - checkout

#       - run:
#           name: Install SPM dependencies
#           command: swift package resolve

#       - run:
#           name: Build project
#           command: |
#             xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"

  # unit-test:
  #   macos:
  #     xcode: "14.0.1"
  #   steps:
  #     - checkout

  #     - run:
  #         name: Install SPM dependencies
  #         command: swift package resolve

  #     - run:
  #         name: Run unit tests
  #         command: |
  #           xcodebuild test -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13" -enableCodeCoverage YES

  # ui-test:
  #   macos:
  #     xcode: "14.0.1"
  #   steps:
  #     - checkout

  #     - run:
  #         name: Install SPM dependencies
  #         command: swift package resolve

  #     - run:
  #         name: Run UI tests
  #         command: |
  #           xcodebuild test -project TestCICD.xcodeproj -scheme UITests -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"






