version: 2.1
jobs:
  build:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout

      # # Khóa cache cho SPM
      # - restore_cache:
      #     keys:
      #       - spm-cache-{{ .Branch }}-{{ checksum "Package.resolved" }}

      # - run:
      #     name: Install SPM dependencies
      #     command: swift package resolve

      # # Lưu cache cho SPM
      # - save_cache:
      #     key: spm-cache-{{ .Branch }}-{{ checksum "Package.resolved" }}
      #     paths:
      #       - ~/.build

      - run:
          name: Build project
          command: |
            xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"
      - store_artifacts:
          path: build/reports
      - store_artifacts:
          path: build/coverage
