# version: 2.1
# jobs:
#   build:
#     macos:
#       xcode: "14.0.1"
#     steps:
#       - checkout

#       - run:
#           name: Build project
#           command: |
#             xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"
#       - store_artifacts:
#           path: build/reports
#       - store_artifacts:
#           path: build/coverage




version: 2.1
jobs:
  build:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout

      - restore_cache:
          keys:
            - spm-cache-v1-{{ checksum "Package.resolved" }}
            - spm-cache-v1-

      - run:
          name: Resolve Packages
          command: swift package resolve

      - run:
          name: Build project
          command: |
            xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project TestCICD.xcodeproj -scheme TestCICD -destination "platform=iOS Simulator,OS=15.5,name=iPhone 13"

      - save_cache:
          key: spm-cache-v1-{{ checksum "Package.resolved" }}
          paths:
            - .build

      - store_artifacts:
          path: build/reports
      - store_artifacts:
          path: build/coverage